Red [
    Title:   "Registry for redpm"
    Author:  "ANLACO"
    File:    %src/registry.red
    Purpose: {Read/write deps.red and deps.lock and transform to/from package ADT}
]

registry: context [

    ;-- Default locations (public)
    deps-dir: %deps/
    deps-file: %deps.red
    lock-file: %deps.lock

    ;-- Read deps.red and return a block of package! objects or none
    load-packages: func [/local data packages name url u result] [
        unless exists? deps-file [return none]
        data: attempt [load deps-file]
        unless data [return none]

        packages: copy []
        foreach [name url] data [
            ;-- Validate input using the barricade
            unless validator/valid-package-name? to-string name [
                logger/log-warn rejoin ["Skipping invalid package name: " to-string name]
                continue
            ]
            unless validator/valid-url? (either url [url][to-string url]) [
                logger/log-warn rejoin ["Skipping invalid URL for " to-string name ": " to-string url]
                continue
            ]

            ;-- url can be string! or url! — normalize to url!
            either url? url [u: url][
                result: attempt [to url! url]
                either result [u: result][u: to url! to-string url]
            ]
            append packages package/make-package to-string name u
        ]
        packages
    ]

    ;-- Write a simple deps.red from a block of package objects
    save-packages: func [packages [block!] /local content pkg] [
        content: copy ["["]
        foreach pkg packages [
            append content rejoin ["    " package/get-name pkg " " to-string package/get-url pkg]
        ]
        append content "]"
        write/lines deps-file content
        true
    ]

    ;-- Load lockfile (simple placeholder - returns none if absent)
    load-lockfile: func [/local res] [
        unless exists? lock-file [return none]
        attempt [load lock-file]
    ]

    ;-- Save lockfile (basic implementation)
    save-lockfile: func [entries [block!] /local out] [
        ; entries expected to be block! of objects or strings - write as-is
        ; For now write a comment and the entries serialized by mold
        out: rejoin [";-- Generated by redpm\n" mold entries]
        write lock-file out
        true
    ]

    ;-- Create default deps.red (used by init)
    create-default-config: func [] [
        either exists? registry/deps-file [
            logger/log-warn rejoin [to-string registry/deps-file " already exists"]
            false
        ][
            write registry/deps-file {[
    ;-- Add your dependencies here
    ;-- Format: PackageName "https://github.com/user/repo"

    ;-- Example:
    Red-Utils "https://github.com/ANLACO/Red-Utils"
]}
            logger/log-ok "Created deps.red"
            true
        ]
    ]
]
